version: "3.7"
services:
    # Docker Hub: https://hub.docker.com/repository/docker/socialpjames/socialplaces-developer-test
    application:
        hostname: application
        image: socialpjames/socialplaces-developer-test:20230126
        restart: unless-stopped
        env_file:
            - ./docker/docker.env
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - ./vendor:/var/www/html/vendor:delegated
            - ./node_modules:/var/www/html/node_modules:delegated
            - /var/www/html/var
            - /var/www/html/public/build
        networks:
            - backend
        ports:
            - 80:80
            - 443:443
        logging:
            options:
                max-file: "1"
                max-size: "1m"
        stdin_open: true
        tty: true
networks:
    backend:
        driver: 'bridge'
